version: "3.9"

services:
    sqlserver:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "averygoodpasswordForMe!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
